//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Felix.MarketData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bar
    {
        public int BarId { get; set; }
        public int ContractId { get; set; }
        public double Open { get; set; }
        public double High { get; set; }
        public double Low { get; set; }
        public double Close { get; set; }
        public Nullable<int> Volume { get; set; }
        public int Period { get; set; }
        public System.DateTime Time { get; set; }
        public int Index { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
